apiVersion: apps/v1
kind: Deployment
metadata:
  name: citytwin
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: citytwin
  template:
    metadata:
      labels:
        app: citytwin
    spec:
      containers:
      - name: citytwin
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
